drop table analyses_viewers;
drop table profiles;
drop table analyses;

create table profiles
(
    id           bigint generated by default as identity
        primary key,
    name         varchar(255),
    surname      varchar(255),
    budget       numeric,
    created_time timestamp not null,
    updated_time timestamp not null
);
create table analyses
(
    id           bigint generated by default as identity
        primary key,
    type         varchar(255),
    owner_id     bigint,
    hidden_info  varchar(255),
    created_time timestamp not null,
    updated_time timestamp not null
);

create table analyses_viewers
(
    id          bigint generated by default as identity
        primary key,
    analyses_id bigint not null
        constraint analyses_id_fk1
            references analyses,
    viewers_id  bigint not null
        constraint viewers_id_fk2
            references profiles
);

alter table analyses_viewers
    owner to personal_project;

create index viewers_id_address
    on analyses_viewers (viewers_id desc);

alter table analyses
    owner to personal_project;

alter table profiles
    owner to personal_project;

create index profile_id_address
    on analyses (owner_id desc);

insert into profiles(id, name, surname, budget, created_time, updated_time)
values (2, 'test name', 'test surname', 1000, current_timestamp, current_timestamp);
insert into profiles(id, name, surname, budget, created_time, updated_time)
values (3, 'test name 3', 'test surname 3', 10000, current_timestamp, current_timestamp);